config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "lists#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :lists do
    resources :pages, only: [ :edit, :update, :destroy ]
  end
  resources :lists do
    resources :bookmarks
  end
  get "dashboard", to: "pages#dashboard"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks
  belongs_to :user
end

app/models/movie.rb
class Movie < ApplicationRecord
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = List.find(params[:list_id])
    @bookmark.save
    redirect_to dashboard_path(@pages)
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.user = current_user
    @list.save
    redirect_to dashboard_path
  end

  def edit
  end

  def update
    @list.update(list_params)
    redirect_to dashboard_path
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name, :genre)
  end

  def set_list
    @list = List.find(params[:id])
  end
  
  def set_user
    @list.user = current_user
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def dashboard
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoviesLovers</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body><%= render "shared/navbar" %>
  <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.input :genre %>
  <%= f.submit %>
<% end %>

app/views/lists/edit.html.erb
<h1>EDIT YOUR LIST</h1>

<%= render "form", list: @list %>


  <%= link_to "Delete",
  list_path(@list),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>

  <%= link_to "Edit", edit_list_path(@list) %>
  <%= link_to "Add movie", new_list_bookmark_path(@list)%>

app/views/lists/index.html.erb
<h1>WELCOME TO MY WEBSITE</h1>

<h2>WE HAVE MANY MOVIE LISTS HERE, LOOK</h2>

<ul>
  <% @lists.each do |list| %>
    <li><%= list.name %></li>
    <%= list.genre %>
  <% end %>
</ul>

<h2>BUT HOW ABOUT YOU CREATE YOUR OWN MOVIE LIST?</h2>

<%= link_to "New list",
  new_list_path(@list) %>

<h3>Go to the dashboard</h3>
  <%= link_to "Dashboard",
  dashboard_path(@pages) %>

app/views/lists/new.html.erb
<%= simple_form_for(list) do |f| %>
  <%= f.input :name %>
  <%= f.input :genre %>
<% end %>

app/views/lists/show.html.erb
<p><strong><%= @list.name %> <%= @list.genre %></strong></p>
  <div class="list-group">
    <% @list.movies.each do |movie| %>
    <li><%= movie.title %></li>
    <li><%= movie.year %></li>
    <li><%= movie.description %></li>
    <li><%= movie.poster_url %></li>
    <li><%= movie.rating %></li>
    <li><%= link_to "remove this movie", list_bookmark_path(@list.movies), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></li>
    <% end %>
  </div>

  <%= link_to "Delete", list_path(@list), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
  <%= link_to "Edit", edit_list_path(@list) %>

app/views/pages/dashboard.html.erb
<h1>DASHBOARD</h1>
<h1> This is my Dashboard</h1>
<ul id="lists">
<% @user.lists.each do |list| %>
  <li>
  <!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal-<%= list.id%>">
  <%= list.name %> <%= list.genre %>
</button>
<!-- Modal -->
<div class="modal fade" id="exampleModal-<%= list.id%>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"> <%= list.name %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Please edit or delete your list
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"> <%= link_to "Add movie", new_list_bookmark_path(list)%> </button>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"> <%= link_to "Edit", edit_list_path(list)%> </button>
        <button type="button" class="btn btn-primary"> <%= link_to "Delete", list_path(list), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></button>
      </div>
    </div>
  </div>
</div>
  </li>
<% end %>
</ul>

app/views/pages/home.html.erb
<h1>WELCOME TO MY WEBSITE</h1>

<h2>WE HAVE MANY MOVIE LISTS HERE, LOOK</h2>


<h2>BUT HOW ABOUT YOU CREATE YOUR OWN MOVIE LIST?</h2>

<%= link_to "New list",
  new_list_path(@list) %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", lists_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>